M48
; DRILL file {KiCad (7.0.0)} date Tue May 30 12:42:43 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-30T12:42:43-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X3.6614Y-3.5236
X3.6614Y-3.6969
T2
X4.1142Y-2.3583
X4.122Y-4.9882
X7.7087Y-2.3701
X8.1772Y-4.937
T0
M30
